# -*- coding: utf-8 -*-
{
    'name': "Tti Sale Order Customizations",
    'summary': "Tti Sale Order Customizations",
    'description': """Tti Sale Order Customizations""",

    'author': "Visiomate",
    'company': 'Visiomate',
    'maintainer': 'Visiomate',
    'website': "https://www.visiomate.com",

    'category': 'Sales',
    'license': 'LGPL-3',
    'version': '1.0.3',
    'sequence': -200,

    'depends': [
        'base', 'sale', 'sale_management', 'sales_team', 'product', 'purchase', 'account', 'purchase', 'crm',
        'report_xlsx',
        'visio_tti_partner_api_fields',
        'hr', 'contacts'
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/mts_sale_order_sequence.xml',
        'data/tti_parcels_sequence.xml',
        'data/sale_order_no.xml',
        'data/mail_template.xml',
        'wizard/so_package_difference.xml',
        'views/tti_parcels_views.xml',
        # 'views/account_payment_register.xml',
        'views/sale_order_views.xml',
        'views/target_achieved.xml',
        'views/tti_division.xml',
        'views/tti_city_views.xml',
        'views/product_pricelist.xml',
        'views/tti_city_zone_views.xml',
        'views/tti_parcel_courier_views.xml',
        'views/tti_so_lims_tests_status_logs_views.xml',
        'views/tti_pi_brand_views.xml',
        'views/tti_si_category_views.xml',
        'views/tti_si_dye_stuff_views.xml',
        'views/tti_si_fiber_views.xml',
        'views/tti_si_uom_views.xml',
        'views/tti_si_program_views.xml',
        'views/tti_si_dosage_form_views.xml',
        'views/tti_si_department_views.xml',
        'views/tti_si_test_group_views.xml',
        'views/tti_si_sub_category_views.xml',
        'views/tti_si_product_type_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/menus.xml',
        # 'views/res_users.xml',
        # 'wizard/party_invoice_detail.xml',
        # 'report/party_invoice_detail.xml',
    ],
    'demo': [],

    'images': ['static/description/banner.png'],
    'application': True,
    'installable': True,
    'auto_install': False,
}
